{% set version = "1.6.4.dev0" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: d0a6b29f72a13f08e008b9becff247cc75c84acb213332ede18879c5b6aa4dfd
  patches:
    - backport_319.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.20                       # [build_platform != target_platform]
    - numpy >=2.0.0rc1                       # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.20
    - numpy >=2.0.0rc1
  run:
    - python
    - numpy >=1.23.0

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    - pytest -vv test
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
