{% set version = "1.6.4.post1" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 50ac76cc9f10ab7bd46e44a71c51a6927051b499b4407df4f29ab13d741b942f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.29.20                       # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools >=41.2
    - cython >=0.29.20
    - numpy
  run:
    - numpy
    - python

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    - pytest -vv test
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
