{% set version = "1.1.2" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 60395cb6510903a0412dd5383122d471941a3f31db8645c9d691bc8aa8af899f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
  imports:
    - cftime
  commands:
    - pytest -vv test

about:
  home: https://github.com/Unidata/cftime
  license: MIT and GPL-3.0
  license_file: COPYING
  summary: Time-handling functionality from netcdf4-python

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
