{% set version = "1.3.0" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 8d6a1144f43b9d7a180d7ceb3aa8015b7133c615fbac231bed184a91129f0207

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    - pytest -vv test
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT and GPL-3.0-only
  license_file: COPYING
  summary: Time-handling functionality from netcdf4-python

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
