{% set version = "1.4.0" %}

package:
  name: cftime
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cftime/cftime-{{ version }}.tar.gz
  sha256: 2c6fe0279b1913ea7c67fbe020a736d5740cd21e4f81a10f91260267681795d7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  source_files:
    - test
  requires:
    - pytest
    - pip
  imports:
    - cftime
  commands:
    - pytest -vv test
    - pip check

about:
  home: https://github.com/Unidata/cftime
  license: MIT
  license_file: LICENSE
  summary: Time-handling functionality from netcdf4-python

  description: |
    Time-handling functionality from netcdf4-python
  doc_url: https://github.com/Unidata/cftime
  dev_url: https://github.com/Unidata/cftime

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
